### PR TITLE
Clippy fixes

### PR DESCRIPTION
**Pull request by picobyte**
I tried to resolve some clippy fixes, some of which you also seem to have addressed, a little differently. Please do not merge blindly but consider the changes. 
16cce5d touches lots of files due to the RcRfc<T> type that was added for a Rc<RefCell<T>>. It cleans up code, I think, but could be difficult to merge if you have pending changes. I think I resolved what  conflicted with your latest changes - it compiles and seems to run.

### CODE REVIEW

**Comment by Grokmoo** [comment]
Hi!  This is a large PR and I definitely appreciate the effort!

It looks like you have replaced a lot of instances of Rc<RefCell<_>> with the RcRfc<_> type, in the widget and GUI library.  I think I am ok with this as I have no plans to "fix" the GUI to not use Rc<RefCell<_>>.  It might be worthwhile to try to hide this as an implementation detail inside the core widget classes at some point.

I would not want to make this change in other parts of the code where eventually I would like to get rid of Rc<RefCell<_>>.  Such as in dealing with EntityState.  I don't think you have done that though.

It also looks like you have decreased the number of arguments in many functions through the use of the ScalePoint struct.  I have very similar code locally that I haven't checked in - although I think I prefer a more fine grained approach with separate structs for the different components.

**Comment by picobyte** [comment]
Now I look at what the RefCell and Rc do, I think this is working around the default referencing and borrowing; it would probably be best to resolve these, if possible. I'm guessing these were difficult to resolve, but I'll give it a try.

**Comment by Grokmoo** [comment]
Apologies; I'm not suggesting you try to fix entity_state to not use Rc<RefCell<_>>.  This will be very subtle and require major rework of a bunch of pieces.

**Comment by picobyte** [comment]
No problem, I was just looking at it. I know some rust, but I've not worked on such a large project before. Concerning the Scalepoint struct, that was my last patch, so I think that could just be removed.

**Comment by picobyte** [comment]
I changed all the Rc<RefCell<T>> cases, so that included EntityState as well. Maybe this one commit is just too much and I should break it up per T.

**Comment by picobyte** [comment]
Sorry, maybe the pull without isn't worth it, there's only the new/generate change left, it looks like everything else was already resolved.

**Comment by Grokmoo** [comment]
Thanks, I appreciate your help.

**Pull request merged**
